version: 2
jobs:
  build-job:
    docker:
      - image: circleci/python:3.6.2
    
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: sudo pip install -r requirements.txt
  
  deploy-job:
    docker:
      - image: google/cloud-sdk
    steps:
      - run:
        name: Store Service Account
        command: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json

      - run: sudo gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
      - run: sudo gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
      - run: sudo gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE

      - run:
        name: Deploy Master to GKE
        command: ./deploy.sh

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
        requires:
          - build
        filters:
          branches:
            only: master
